### ISSUE TITLE
socket is triggered twice

### ISSUE THREAD

**Issue by GuillaumeCisco** [webpack-contrib/webpack-hot-client#25]
* Operating System: linux
* Node Version: 9.5.0
* NPM Version: 5.6.0
* webpack Version: 4.0.1
* webpack-hot-client Version: 2.0.0

- [x] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Code

```js
  // webpack.config.js
```

```js
  // additional code, remove if not needed.
```

### Expected Behavior
Webpack hot client websocket connects once
### Actual Behavior
Webpack hot client websocket connects twice

I've in the console of chrome dev tools:
```
log.js:48 ｢hot｣ Hot Module Replacement Enabled. Waiting for signal.
log.js:48 ｢hot｣ WebSocket connected
log.js:48 ｢hot｣ Hot Module Replacement Enabled. Waiting for signal.
log.js:48 ｢hot｣ WebSocket connected
log.js:48 ｢hot｣ App Updated, Reloading Modules
```
I have two websocket connections.

### For Bugs; How can we reproduce the behavior?

Use webpack 4.

**Comment by shellscape** [comment]
> Please fill out _ALL_ fields, or your issue may be closed as "invalid."

You didn't provide any code or any information on your setup. So we can't help you. If you'd like to follow the instructions and fill in the missing code, we'll reopen the issue.

**Comment by GuillaumeCisco** [comment]
Seriously?!

There's no code to display.

**Comment by GuillaumeCisco** [comment]
I'm going to assume you don't have much experience with github / open source projects. The project does not provide a `CHANGELOG.md` or `history.md` file for tracking changes and support.
We can't know if the project supports webpack 4 in this entire project. It is not precised in the README.md file either.

You can know the context in which I'm using the module, WITHOUT CODE as I just tested this project in a migration to webpack 4.
Closing this issue without reading it and not asking questions for understanding it better is a big problem.

It is not reasonable to close issue because the template issue does not include all the cases.
There is a problem with webpack 4 testing in my case. By not changing the code at all.

Does webpack-hot-client have been reported to correctly support webpack 4? Having this information is a start.
Some people cannot share their projects if there are private.
Luckily, my project is public, you can test it on https://github.com/GuillaumeCisco/guillaumecisco/tree/gcisco-webpack-4

Hope it will help.

**Comment by shellscape** [comment]
> I'm going to assume you don't have much experience with github / open source projects. The project does not provide a CHANGELOG.md or history.md file for tracking changes and support

Every Github project has a releases page. https://github.com/webpack-contrib/webpack-hot-client/releases. It's a maintainer's discretion to use that page to list release changes, or a separate changelog. Your inexperience is showing here. 

> We can't know if the project supports webpack 4 in this entire project. It is not precised in the README.md file either.

That's also false, and may be due to inexperience: https://github.com/webpack-contrib/webpack-hot-client/blob/master/package.json#L31. `peerDependencies` clearly shows which version of webpack is required. This is an npm norm.

> You can know the context in which I'm using the module, WITHOUT CODE as I just tested this project in a migration to webpack 4.

You're not getting it. We can't understand your environment if you provide no details. That means providing your code or something that can be used to reproduce. 

> Closing this issue without reading it and not asking questions for understanding it better is a big problem.

Sorry, but you're incorrect there. The issue template contains a warning that skipping fields of the template will result in a status of invalid, and closing the issue.

Your responses have been pretty unreasonable and we're going to decline to triage your issue. Best of luck in your project. If you'd like to use an alternative, please check out `webpack-hot-middleware`.
