### ISSUE TITLE
Allow specifying client "server host" independently (from server "host")

### ISSUE THREAD

**Issue by nmschulte** [webpack-contrib/webpack-hot-client#30]
* Operating System: `Linux desmas-l.desmas 4.15.0-1-amd64 #1 SMP Debian 4.15.4-1 (2018-02-18) x86_64 GNU/Linux` `buster/sid`
* Node Version: `v9.6.0`
* NPM Version: `5.6.0`
* webpack Version: `4.1.1`
* webpack-hot-client Version: `2.0.0`

- [ ] This is a **bug**
- [x] This is a **feature** request
- [x] This is a **modification** request

### Code

```js
  // webpack.config.js
```

### For Features; What is the motivation and/or use-case for the feature?
It's conceivable that the client will be configured to connect to the server via a different host/port.  This can be accommodated with minimal code change, simply by allowing to specify a different host/port for the client.

For example, imagine the server (`webpack-hot-client`, and thus `webpack` proper) is running on a hypervisor guest ("inside a virtual machine"; Vagrant, etc.), or contained inside an LXC container (Docker), or behind a reverse proxy, or even on a remote machine.  As it stands, the codes assume the client environment is the same as the server and forces the use of the server options (https://github.com/webpack-contrib/webpack-hot-client/blob/master/index.js#L55).

Trivially, this could be done by allowing a `webSocket.host`/`webSocket.port` `option` (https://github.com/webpack-contrib/webpack-hot-client#clientcompiler-options).  This could be improved/normalized however appropriate.

Less trivially, and more generally, the codes could check for a `webpack-hot-client/client` entry before augmenting and skip the step if it exists.  This would allow a user-in-the-know to manually configure all of the client options (if I understand the code correctly, that is).

My particular use-case is "containerized build via Docker," and using `0.0.0.0` as the `host` option gets me what I need, but is a real hack (as the client connects to the socket on `ws://0.0.0.0`, and `0.0.0.0` is not required to resolve, though implementations tend to allow it: https://unix.stackexchange.com/questions/419880/connecting-to-ip-0-0-0-0-succeeds-how-why)

**Comment by shellscape** [comment]
> Less trivially, and more generally, the codes could check for a webpack-hot-client/client entry before augmenting and skip the step if it exists. This would allow a user-in-the-know to manually configure all of the client options (if I understand the code correctly, that is).

Without snark of any kind, I'm lost. I'm not sure which code (psa: no one really says _codes_) you're referencing there. If you're saying that code should run a check in the client, then it could simply attempt a `require` of a module bundled from `webpack-hot-client/client` in a `try/catch` and on error that would mean the entry wasn't available. I'm not sure what you're speaking of with regard to configuring hot client options at that point (as that's not something that should be done - since at that point the client and server will be out of sync, which would be bad)

> As it stands, the codes assume the client environment is the same as the server and forces the use of the server options (https://github.com/webpack-contrib/webpack-hot-client/blob/master/index.js#L55).

Going backwards to the beginning of the issue; this sounds like you want the `WebSocket` server to listen on a `host:port#A`, and the client code to connect a `WebSocket` to a separate `host:port#B`. While I can see where the use-case exists, and I can see how that might seem to be slightly more straightforward, that'll actually introduce ambiguity. If you have a server environment that is running a server, on which the `WebSocket` server (WSS) is listening, proxies should be setup and managed by that dev environment to provide the proper proxying, redirects, rewrites etc to that server address. You're getting into tricky territory here for sure.

Here's a few more bits on `0.0.0.0` vs `127.0.0.1` vs `localhost` and how they all affect routing:
https://www.howtogeek.com/225487/what-is-the-difference-between-127.0.0.1-and-0.0.0.0/ (great explanation)
https://stackoverflow.com/questions/20778771/what-is-the-difference-between-0-0-0-0-127-0-0-1-and-localhost

You might also consider using IPv6 for this: https://stackoverflow.com/questions/40189084/what-is-ipv6-for-localhost-and-0-0-0-0

I can see the use-case here, but I'm not sure it's something in high enough demand to introduce. Especially given that there's a reasonable workaround.

**Comment by nmschulte** [comment]
> Closed in #34

Thank you Andrew, this is much appreciated.  I'm sorry this issue has sort of boiled over; it seems like I set us off on the wrong foot.

I suspect the intention of `webpack-hot-client` was to blur the distinction between the server (WSS and its hosting process) and the client, so that the developer has a single configuration to worry about.

In my eyes, the real value of `webpack-hot-client` is the ability to move away from Webpack dev-server.  Webpack dev-server changes how Webpack produces build-artifacts, implicating the hosting environment, which drives a wedge in the "debug/development run-time is identical to release/production run-time" principle.  There is a plugin that tries to accommodate this scenario ([`write-file-webpack-plugin`](https://github.com/gajus/write-file-webpack-plugin)) but forgoing the problem and using the simpler `webpack-hot-client` is a much better solution (fewer moving parts, more re-use/identical run-time).

**Comment by nmschulte** [comment]
I forgot to ask: for the same reason to separate the client and server `host`, can we also separate the `port`?  Consider that the same situation where "client & server hosts don't match" could have been resolved with a proxy different client & server ports.

**Comment by shellscape** [comment]
re: allowing different ports - that's jumping the shark, and I'm not going to encourage a bad practice by allowing that. Your WebSocket ports should always be identical (and yes, folks running this on docker will scream). That's a best practice, and one that's going to hold fine for 99% of use cases. You'll have to perform some tricky proxying on your end if that's something you're in need of. `webpack-hot-client` is here as a convenience, but it's not here to solve the never-ending world of dev scenarios.

**Comment by EricMCornelius** [comment]
@shellscape - not being able to configure the port for the browser client and the server independently means it's not possible to run behind a reverse proxy running on the same machine (with webpack-serve anyway), since the proxy and webpack-serve are going to need to listen on the same port.
@shellscape - not being able to configure the port for the browser client and the server independently means it's not possible to run behind a reverse proxy running on the same machine (with webpack-serve anyway), since the proxy and webpack-serve are going to need to listen on the same port.

That seems somewhat restrictive to me - it's a fairly common situation in an enterprise setting to have operations control a reverse proxy configurations with only port 443 ssl inbound access, running multiple virtual hosts behind it for developers to utilize in their own port space.

Much as I realize that you may intend this tooling only for local development purposes and find this overkill - there's actually a lot of nice utility in being able to share a hot reload view of a page with designers, managers, etc. while modifying elements (or more often, style sheets).  This makes running a hot reload server on shared, secured, publicly accessible infrastructure a fairly desirable use-case.

Any chance of convincing you on this?

**Comment by shellscape** [comment]
@EricMCornelius what you've got there is an edge case. For your situation, I would recommend forking both webpack-serve and webpack-hot-client and installing via git repo link in package.json - that would be fairly trivial to do (and webpack-serve actually does that with several koa modules that insist on not supporting Node 6). Forking like this is super easy, and you can read about how to keep a fork up to date with "upstream" [here](https://help.github.com/articles/syncing-a-fork/).

**Comment by EricMCornelius** [comment]
@shellscape - I've already forked and made changes similar to those in this pr. Mostly, wondering if you'd accept them being contributed back upstream for the community, since I think there's quite a few folks out there that will need the same functionality.

**Comment by shellscape** [comment]
@EricMCornelius appreciate the offer but I think that introduces too much complexity for too little value to the userbase as a whole. We'll pass on that for now.

**Comment by EricMCornelius** [comment]
@nmschulte feel free to use my fork if you need configurable ports as well.  Uses the same syntax as the hosts from this pr.

```port: {client: <client_port>, server: <server_port}```

Unfortunately, webpack-serve required some minimal changes as well, based on how it tries to allocate a hot port (if attempting to listen on a privileged one) and inject it to webpack-hot-client.

**Comment by bennidhamma** [comment]
I actually don't think that this particular issue is that tough for docker users, because it's pretty easy to port map with docker containers. 

But, in general, as I've been reading these bug reports these past 5 days as I've been struggling to get webpack-serve to work in our environment, it does seem odd to read the various posts by you, @shellscape that seem so dismissive of docker as a target environment. In my experience, it's becoming a pretty standard way to develop: [dev/prod parity](https://12factor.net/dev-prod-parity) is a good practice, so if your team deploys into kubernetes or docker, using docker in your dev env is pretty important.

Ordinarily, I get that it's the prerogative of the project owner to have any sort of attitude they want, to choose what kind of culture accompanies their open source project, and to decide which features get in, which bugs get in and so forth.

But in this case, the old webpack-dev-server has been deprecated, and there is now a notice which tells users to come and use this project. So to find out that because our development environments don't mirror the project owners, we are automatically not part of "the 99%" use case is pretty disheartening.

Reducing functionality and support doesn't feel like an improvement. Cutting out support for something as ubiquitous as docker feels like a misstep for the webpack community.

I know that "we can just fork and start a new project" or whatever, and I guess, if you really don't want to support docker, that may be the best path forward for everyone's health. But I wouldn't want to do that without your blessing @shellscape. I've gathered from your replies to folks that you don't *seem* interested in supporting the docker use case, but maybe I'm just being too sensitive / reading too much in.

Do you have a preference? Would you like to just see us docker users 'go away'? Or would you consider accepting PRs, having discussions, etc, in the interest of supporting docker users as first class citizens?

**Comment by shellscape** [comment]
@bennidhamma It sounds like you've read into discussions you've been observing a bit too negative, and yes, overly sensitive. If you'd like to have a discussion about my approach or share your thoughts about philosophy on a project, please use another channel like twitter, slack, email, or gitter. I'm easily accessible via all those channels. Issues aren't the right place for opining about a maintainer's philosophy (And that's said without snark). Please avoid doing so in `webpack-contrib` repos moving forward.

You'll notice that different client and server hosts was eventually added https://github.com/webpack-contrib/webpack-hot-client#host, and a renewed discussion for separate server and client ports with an outstanding contributor making a solid case for the feature: https://github.com/webpack-contrib/webpack-hot-client/issues/79.

I also disagree with your assessment that docker users aren't being treated as first class citizens. I use it daily for my 9-5 job, and CI for every repo in `webpack-contrib` makes use of docker. I think this is simply an opportunity to step back and have a breath before reacting (perhaps a few more breaths if you've been sitting on that reply for a while.) The _extremely high bar_ for new features isn't relegated to a particular user-base, and attempting to shame a maintainer into caving is something I'm particularly immune to (and I tend to have an opposite allergic reaction to it). There are insane expectations in the webpack ecosystem that a tool for it should perform every action every user desires - and it's exactly why tools like webpack-dev-server are an unmaintainable mess. It's why many of the projects in webpack have so many breaking changes for each major version. When an ecosystem is so vast, and the user-base so wide, there is an immense duty to carefully, methodically, and be damn sure something should be added to a project before it is done so. You will run into that high bar on any number of other projects. And I dare say won't even receive the same level of consideration. If that makes you feel under-represented, slighted, or whatnot... we'll I'm sorry about that. But taking it personally is silly. And yes, you are _always welcome to fork with no hard feelings._

I will be locking this thread as off-topic, as it's veered way off the path with the last comment. And again, you're welcome to contact me another way if you'd like to discuss your ideas and opinions about how the project is managed and maintained.
